version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "fix"
      include: "scope"
    rebase-strategy: "auto"
    allow:
      - dependency-type: "direct"
    security-updates-only: true
