services:
  qualificamais-api:
    container_name: qualifica-api
    image: matheusazr/qualifica-api:latest
    ports:
      - "80:3000"
    env_file:
      - .env
    restart: unless-stopped
  database:
    container_name: ${POSTGRES_HOST}
    image: postgres:17.5-alpine3.21
    ports:
      - "10133:5432"
    env_file:
      - .env
    volumes:
      - postgresdata:/var/lib/postgresql/data
    restart: unless-stopped


volumes:
  postgresdata:
